[msg TRL_001_0_0 [Quick Fortunes]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Drawing a [uf 0 1 2]Quick[uf 0 1 27] Fortune will deepen your relationship a small amount, but will not cause time to pass.[n][uf 1 1][e]

[msg TRL_001_0_0 [Pious Fortunes]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Drawing a [uf 0 1 2]Pious[uf 0 1 27] Fortune will deepen your relationship a large amount while causing time to pass. If your bond has been damaged, it may also be repaired.[n][uf 1 1][e]

[msg TRL_001_0_0 [Pious Fortunes]]
[uf 0 5 65278][uf 2 1][uf 4 8 0]Additionally, a [uf 0 1 2]Pious[uf 0 1 27] Fortune may have an effect on your wallet, for better or for worse.[n][uf 1 1][e]